export type Currency = { code: string; label: string; symbol: string; flagCode: string };

// flagCode is an ISO 3166-1 alpha-2 code (lowercase) for the "flag-icons"
// package's `fi fi-<code>` class — real SVG flags, not Unicode emoji, since
// Windows renders flag emoji as plain two-letter codes with no color.
//
// Matches BitValve/SafeTheTrade's pattern of supporting a large set of local
// fiat currencies rather than a handful of majors — grouped by region below
// for readability, not in the dropdown itself.
export const CURRENCIES: Currency[] = [
  // Americas
  { code: "USD", label: "US Dollar", symbol: "$", flagCode: "us" },
  { code: "CAD", label: "Canadian Dollar", symbol: "CA$", flagCode: "ca" },
  { code: "MXN", label: "Mexican Peso", symbol: "MX$", flagCode: "mx" },
  { code: "BRL", label: "Brazilian Real", symbol: "R$", flagCode: "br" },
  { code: "ARS", label: "Argentine Peso", symbol: "AR$", flagCode: "ar" },
  { code: "CLP", label: "Chilean Peso", symbol: "CL$", flagCode: "cl" },
  { code: "COP", label: "Colombian Peso", symbol: "CO$", flagCode: "co" },
  { code: "PEN", label: "Peruvian Sol", symbol: "S/", flagCode: "pe" },
  { code: "UYU", label: "Uruguayan Peso", symbol: "$U", flagCode: "uy" },
  { code: "VES", label: "Venezuelan Bolívar", symbol: "Bs.", flagCode: "ve" },
  { code: "BOB", label: "Bolivian Boliviano", symbol: "Bs", flagCode: "bo" },
  { code: "PYG", label: "Paraguayan Guaraní", symbol: "₲", flagCode: "py" },
  { code: "GTQ", label: "Guatemalan Quetzal", symbol: "Q", flagCode: "gt" },
  { code: "HNL", label: "Honduran Lempira", symbol: "L", flagCode: "hn" },
  { code: "NIO", label: "Nicaraguan Córdoba", symbol: "C$", flagCode: "ni" },
  { code: "CRC", label: "Costa Rican Colón", symbol: "₡", flagCode: "cr" },
  { code: "PAB", label: "Panamanian Balboa", symbol: "B/.", flagCode: "pa" },
  { code: "DOP", label: "Dominican Peso", symbol: "RD$", flagCode: "do" },
  { code: "JMD", label: "Jamaican Dollar", symbol: "J$", flagCode: "jm" },
  { code: "TTD", label: "Trinidad & Tobago Dollar", symbol: "TT$", flagCode: "tt" },
  { code: "BSD", label: "Bahamian Dollar", symbol: "B$", flagCode: "bs" },
  { code: "HTG", label: "Haitian Gourde", symbol: "G", flagCode: "ht" },
  { code: "CUP", label: "Cuban Peso", symbol: "$MN", flagCode: "cu" },

  // Europe
  { code: "EUR", label: "Euro", symbol: "€", flagCode: "eu" },
  { code: "GBP", label: "British Pound", symbol: "£", flagCode: "gb" },
  { code: "CHF", label: "Swiss Franc", symbol: "CHF", flagCode: "ch" },
  { code: "NOK", label: "Norwegian Krone", symbol: "kr", flagCode: "no" },
  { code: "SEK", label: "Swedish Krona", symbol: "kr", flagCode: "se" },
  { code: "DKK", label: "Danish Krone", symbol: "kr", flagCode: "dk" },
  { code: "PLN", label: "Polish Złoty", symbol: "zł", flagCode: "pl" },
  { code: "CZK", label: "Czech Koruna", symbol: "Kč", flagCode: "cz" },
  { code: "HUF", label: "Hungarian Forint", symbol: "Ft", flagCode: "hu" },
  { code: "RON", label: "Romanian Leu", symbol: "lei", flagCode: "ro" },
  { code: "BGN", label: "Bulgarian Lev", symbol: "лв", flagCode: "bg" },
  { code: "ISK", label: "Icelandic Króna", symbol: "kr", flagCode: "is" },
  { code: "UAH", label: "Ukrainian Hryvnia", symbol: "₴", flagCode: "ua" },
  { code: "RUB", label: "Russian Ruble", symbol: "₽", flagCode: "ru" },
  { code: "TRY", label: "Turkish Lira", symbol: "₺", flagCode: "tr" },
  { code: "RSD", label: "Serbian Dinar", symbol: "дин.", flagCode: "rs" },
  { code: "ALL", label: "Albanian Lek", symbol: "L", flagCode: "al" },
  { code: "MKD", label: "Macedonian Denar", symbol: "ден", flagCode: "mk" },
  { code: "BAM", label: "Bosnia-Herzegovina Mark", symbol: "KM", flagCode: "ba" },
  { code: "MDL", label: "Moldovan Leu", symbol: "L", flagCode: "md" },
  { code: "GEL", label: "Georgian Lari", symbol: "₾", flagCode: "ge" },
  { code: "AMD", label: "Armenian Dram", symbol: "֏", flagCode: "am" },
  { code: "AZN", label: "Azerbaijani Manat", symbol: "₼", flagCode: "az" },
  { code: "BYN", label: "Belarusian Ruble", symbol: "Br", flagCode: "by" },

  // Middle East
  { code: "AED", label: "UAE Dirham", symbol: "AED", flagCode: "ae" },
  { code: "SAR", label: "Saudi Riyal", symbol: "SR", flagCode: "sa" },
  { code: "QAR", label: "Qatari Riyal", symbol: "QR", flagCode: "qa" },
  { code: "KWD", label: "Kuwaiti Dinar", symbol: "KD", flagCode: "kw" },
  { code: "BHD", label: "Bahraini Dinar", symbol: "BD", flagCode: "bh" },
  { code: "OMR", label: "Omani Rial", symbol: "OMR", flagCode: "om" },
  { code: "JOD", label: "Jordanian Dinar", symbol: "JD", flagCode: "jo" },
  { code: "ILS", label: "Israeli Shekel", symbol: "₪", flagCode: "il" },
  { code: "LBP", label: "Lebanese Pound", symbol: "L£", flagCode: "lb" },
  { code: "IQD", label: "Iraqi Dinar", symbol: "ID", flagCode: "iq" },
  { code: "YER", label: "Yemeni Rial", symbol: "YR", flagCode: "ye" },

  // Africa
  { code: "NGN", label: "Nigerian Naira", symbol: "₦", flagCode: "ng" },
  { code: "GHS", label: "Ghanaian Cedi", symbol: "₵", flagCode: "gh" },
  { code: "KES", label: "Kenyan Shilling", symbol: "KSh", flagCode: "ke" },
  { code: "ZAR", label: "South African Rand", symbol: "R", flagCode: "za" },
  { code: "EGP", label: "Egyptian Pound", symbol: "E£", flagCode: "eg" },
  { code: "MAD", label: "Moroccan Dirham", symbol: "MAD", flagCode: "ma" },
  { code: "DZD", label: "Algerian Dinar", symbol: "DA", flagCode: "dz" },
  { code: "TND", label: "Tunisian Dinar", symbol: "DT", flagCode: "tn" },
  { code: "ETB", label: "Ethiopian Birr", symbol: "Br", flagCode: "et" },
  { code: "UGX", label: "Ugandan Shilling", symbol: "USh", flagCode: "ug" },
  { code: "TZS", label: "Tanzanian Shilling", symbol: "TSh", flagCode: "tz" },
  { code: "RWF", label: "Rwandan Franc", symbol: "RF", flagCode: "rw" },
  { code: "ZMW", label: "Zambian Kwacha", symbol: "ZK", flagCode: "zm" },
  { code: "MWK", label: "Malawian Kwacha", symbol: "MK", flagCode: "mw" },
  { code: "MZN", label: "Mozambican Metical", symbol: "MT", flagCode: "mz" },
  { code: "XOF", label: "West African CFA Franc", symbol: "CFA", flagCode: "sn" },
  { code: "XAF", label: "Central African CFA Franc", symbol: "FCFA", flagCode: "cm" },
  { code: "BWP", label: "Botswana Pula", symbol: "P", flagCode: "bw" },
  { code: "NAD", label: "Namibian Dollar", symbol: "N$", flagCode: "na" },
  { code: "GMD", label: "Gambian Dalasi", symbol: "D", flagCode: "gm" },
  { code: "GNF", label: "Guinean Franc", symbol: "FG", flagCode: "gn" },
  { code: "CDF", label: "Congolese Franc", symbol: "FC", flagCode: "cd" },
  { code: "AOA", label: "Angolan Kwanza", symbol: "Kz", flagCode: "ao" },
  { code: "MUR", label: "Mauritian Rupee", symbol: "₨", flagCode: "mu" },
  { code: "SDG", label: "Sudanese Pound", symbol: "SDG", flagCode: "sd" },
  { code: "LYD", label: "Libyan Dinar", symbol: "LD", flagCode: "ly" },

  // Asia
  { code: "INR", label: "Indian Rupee", symbol: "₹", flagCode: "in" },
  { code: "PKR", label: "Pakistani Rupee", symbol: "₨", flagCode: "pk" },
  { code: "BDT", label: "Bangladeshi Taka", symbol: "৳", flagCode: "bd" },
  { code: "LKR", label: "Sri Lankan Rupee", symbol: "Rs", flagCode: "lk" },
  { code: "NPR", label: "Nepalese Rupee", symbol: "Rs", flagCode: "np" },
  { code: "CNY", label: "Chinese Yuan", symbol: "¥", flagCode: "cn" },
  { code: "JPY", label: "Japanese Yen", symbol: "¥", flagCode: "jp" },
  { code: "KRW", label: "South Korean Won", symbol: "₩", flagCode: "kr" },
  { code: "HKD", label: "Hong Kong Dollar", symbol: "HK$", flagCode: "hk" },
  { code: "TWD", label: "Taiwan Dollar", symbol: "NT$", flagCode: "tw" },
  { code: "SGD", label: "Singapore Dollar", symbol: "S$", flagCode: "sg" },
  { code: "MYR", label: "Malaysian Ringgit", symbol: "RM", flagCode: "my" },
  { code: "THB", label: "Thai Baht", symbol: "฿", flagCode: "th" },
  { code: "IDR", label: "Indonesian Rupiah", symbol: "Rp", flagCode: "id" },
  { code: "PHP", label: "Philippine Peso", symbol: "₱", flagCode: "ph" },
  { code: "VND", label: "Vietnamese Dong", symbol: "₫", flagCode: "vn" },
  { code: "MMK", label: "Myanmar Kyat", symbol: "K", flagCode: "mm" },
  { code: "KHR", label: "Cambodian Riel", symbol: "៛", flagCode: "kh" },
  { code: "LAK", label: "Lao Kip", symbol: "₭", flagCode: "la" },
  { code: "MNT", label: "Mongolian Tögrög", symbol: "₮", flagCode: "mn" },
  { code: "KZT", label: "Kazakhstani Tenge", symbol: "₸", flagCode: "kz" },
  { code: "UZS", label: "Uzbekistani Som", symbol: "so'm", flagCode: "uz" },
  { code: "AFN", label: "Afghan Afghani", symbol: "؋", flagCode: "af" },

  // Oceania
  { code: "AUD", label: "Australian Dollar", symbol: "AU$", flagCode: "au" },
  { code: "NZD", label: "New Zealand Dollar", symbol: "NZ$", flagCode: "nz" },
  { code: "FJD", label: "Fijian Dollar", symbol: "FJ$", flagCode: "fj" },
  { code: "PGK", label: "Papua New Guinean Kina", symbol: "K", flagCode: "pg" },
];

export function currencySymbol(code: string): string {
  return CURRENCIES.find((c) => c.code === code)?.symbol ?? code;
}
