// Two-level payment-method taxonomy: a rail (category) with a list of
// specific providers under it. An accepted/saved method is identified by the
// string `${rail.label} · ${provider}` everywhere else in the app — no schema
// change needed, since accepted_payment_methods/payment_method/method were
// already plain text/text[] columns.
//
// Provider lists mirror SafeTheTrade's public payment-method catalog
// (GET /api/v1/payment-methods, 776 entries across the same 8 categories),
// fetched 2026-09-04. Names are kept verbatim from that source, including
// its occasional duplicate/odd entries, so this stays a faithful mirror
// rather than a cleaned-up guess.
export type PaymentRail = {
  key: string;
  label: string;
  providers: string[];
};

export const PAYMENT_RAILS: PaymentRail[] = [
  {
    key: "bank_transfer",
    label: "Bank transfers",
    providers: [
      "Abyssinia Bank",
      "Ak Bars Bank",
      "Alfa Bank",
      "Avangard",
      "Awash Bank",
      "Azimo",
      "Banco Brubank",
      "Bancolombia Cash Deposit",
      "Banesco PagoMovil",
      "Banesco PagoMovil SMS",
      "Bank of America",
      "Bank Transfer",
      "Bank Wire",
      "BCS bank",
      "bunq",
      "Capital One 360 P2P Payment",
      "Cashier's Check",
      "Commercial Bank of Ethiopia (CBE)",
      "CBU/CVU",
      "CBU/CVU Transfer",
      "CEFTS (Common Electronic Fund Transfer Switch)",
      "CenterCredit Bank",
      "Check",
      "Chime Instant Transfer",
      "Cifra Bank",
      "CitiBank (Russia)",
      "Credit Europe Bank (Russia)",
      "DOC (Documento de Ordem de Credito)",
      "Domestic Wire Transfer",
      "ECCP",
      "ECS (Electronic Clearing Service)",
      "Express Elixir",
      "EzRemit",
      "FAST (Fast and Secure Transfers)",
      "Faster Payment System (FPS)",
      "Faster Payments",
      "Fawri+",
      "Freedom Bank",
      "Gazprombank",
      "GIP (GhIPSS Instant Pay)",
      "GIRO RealTime24/7",
      "GoBank Money Transfer",
      "GonderAl",
      "Greiðsluveitan",
      "HOFINET",
      "Home Credit Bank(Russia)",
      "IBPS (Internet Banking Payment System)",
      "IMPS Transfer",
      "InstaPay",
      "Interac e-Transfer",
      "Interac Online",
      "International Wire Transfer (SWIFT)",
      "Jusan Bank",
      "K-net",
      "Kaspi Bank",
      "Khipu",
      "Local Bank(Green)",
      "Local Bank(Red)",
      "Local Bank(Yellow)",
      "Mada",
      "Mercantil",
      "MTS Bank",
      "N26",
      "NAPAS (National Payment Corporation of Vietnam)",
      "NEFT (National Electronic Funds Transfer)",
      "Nigeria Bank Transfers",
      "NIP (NIBSS Instant Payment)",
      "NPP (New Payments Platform)",
      "Other Bank Transfer",
      "Otkritie Bank",
      "OTP Bank",
      "OZON Bank",
      "P27",
      "Pago Movil",
      "PayID",
      "Paysend.com",
      "Paysera Money Transfer",
      "PesaLink",
      "Pix",
      "Plăți Instant",
      "PlusGirot",
      "Pochta Bank",
      "PromptPay",
      "Przelewy24",
      "PSB (Promsvyazbank)",
      "Qatar Mobile Payments",
      "Raiffeisen Bank",
      "Rapid Transfer",
      "Remitly",
      "Renaissance Credit Bank",
      "Rocket Remit",
      "Rosbank",
      "Rosselkhozbank",
      "RPP (Real-time Retail Payments Platform)",
      "RPS (Retail Payment System)",
      "RTC (Real-Time Clearing)",
      "RTGS (Real-Time Gross Settlement)",
      "RTP (Real-Time Payments)",
      "RTPE (Real-Time Payment Engine)",
      "Russian Standard Bank",
      "SADAD",
      "SARIE",
      "Sberbank",
      "SBP (FPS)",
      "SCT Inst (SEPA Instant Credit Transfer)",
      "SEPA",
      "SIC (Swiss Interbank Clearing)",
      "Simple Bank App",
      "SoFi Money Instant Transfer",
      "Sofort",
      "Sovkombank",
      "SPEI (Sistema de Pagos Electronicos Interbancarios)",
      "Straksbetalinger",
      "Straksclearingen",
      "TED (Transferencia Eletronica Disponivel)",
      "TEF (Transferencias en Línea)",
      "Tinkoff Bank",
      "Transfast",
      "Transfer365 CA-RD",
      "TransferGo",
      "UniCredit Bank",
      "UPI Transfer",
      "UPI 123PAY",
      "Uralsib Bank",
      "Venezuela Bank Transfers",
      "VTB Bank",
      "Wise (TransferWise)",
      "Xoom Money Transfer",
      "Yandex Bank",
      "YONO (SBI)",
      "Zelle",
      "Zelle Pay",
      "Zengin System",
    ],
  },
  {
    key: "gift_card",
    label: "Gift cards",
    providers: [
      "Adidas Gift Card",
      "Airbnb Gift Card",
      "Aldi Gift Card",
      "Aliexpress Pocket",
      "Amazon Cash",
      "amazon coins",
      "Amazon Gift Card",
      "AMC Theatres Gift Card",
      "American Airlines",
      "American Apparel Gift Card",
      "American Express Gift Card",
      "Americanas Gift Card",
      "ANY Gift Card Code",
      "Any Visa, MasterCard and AmEx Gift Cards",
      "Apex Legends Gift Card",
      "Apple Gift Card (US only)",
      "Apple Store Gift Card",
      "Applebee's Restaurant Gift Card",
      "Arc'teryx Gift Card",
      "Argos Gift Card",
      "ASOS Gift Card",
      "AT&T Gift Card",
      "Babies R Us Gift Card",
      "Banana Republic Gift Card",
      "bank alahli or alinma",
      "Barnes & Noble Gift Card",
      "Bath and Body Works Gift Card",
      "Battlenet.net gift card",
      "Bed Bath & Beyond Gift Card",
      "Belk Gift Card",
      "Best Buy Gift Card",
      "Bitcoins",
      "Bitjem Gift Card",
      "Bitrefill Balance Card",
      "Bitsa Visa Gift Card",
      "Blizzard Gift Card",
      "Booking.com Gift Card",
      "Build-A-Bear Gift Card",
      "Cabela's E-Gift Code",
      "Cabela's eGift Code",
      "Calvin Klein Gift Card",
      "CASHlib Voucher",
      "CashtoCode Voucher",
      "Chewy Gift Card",
      "Chili's Restaurant Gift Card",
      "China Telecom Card",
      "Cineworld Gift Card",
      "Coles Gift Card",
      "Colourpop Gift Card",
      "Costco Cash Card",
      "Cracker Barrel Gift Card",
      "Credit Card or Debit Card",
      "Crypto Voucher",
      "Curry Gift Card",
      "Currys PC World gift card",
      "CVS Gift Card",
      "CVS Pharmacy Gift Card",
      "David Jones Gift Card",
      "Dell Gift Card",
      "Delta Air Lines Gift Card",
      "Delta Gift Card",
      "DENT",
      "Dick's Sporting Goods Gift Card",
      "Discord Gift Card",
      "Disney Gift Cards",
      "DMM Prepaid Card",
      "Dollar General Gift Card",
      "Domino's Pizza Gift Card",
      "DoorDash Gift Card",
      "Dunkin' Donuts Card",
      "EA Play Gift Card",
      "Eastbay Gift Card",
      "EB Games Gift Card",
      "eBay Gift Card",
      "eGifter.com Code",
      "Eneba Gift Card",
      "Etsy",
      "Everlane Gift card",
      "Fandango Gift Card",
      "Finish Line Gift Card",
      "Flexepin Gift Card",
      "Flipkart e-Gift Voucher",
      "Foot Locker Gift Card",
      "Forever 21 Gift Card",
      "Fortnite V-Bucks",
      "FreshDirect Gift Card",
      "G2A Gift Card",
      "Gamestop Gift Card",
      "Gamivo Gift card",
      "Gap Gift Card",
      "Gift Card Steam (Valve) Digital Wallet Code",
      "Gift Cards (Miscellaneous Retailers)",
      "gift cards of us based retailers",
      "Giftcards.nl Redeem choice card",
      "Google Play Gift Card",
      "Groupon Gift Card",
      "Grubhub Gift Card",
      "Guitar Center Gift Card",
      "Gyft.com code",
      "Happy card gift cards",
      "HEMA Gift Card",
      "H&M Gift Card",
      "Holiday",
      "Home Depot Gift Card",
      "Hooters Gift Card",
      "Hotels.com Gift Card",
      "HULU Gift Card",
      "Hyatt eGift Card",
      "IHOP Gift Card",
      "Ikea Gift Card",
      "imo Gift Card",
      "IMVU Gift Card",
      "Instacart Gift Card",
      "iTunes Gift Card",
      "Jason's Deli Gift Cards",
      "Jawaker Pins Card",
      "JCPenney Gift Card",
      "JD.com gift cards",
      "Jomashop Gift Card",
      "Karma Koin",
      "Kinguin Gift card",
      "Kohl's Store Gift Card",
      "League of Legends/Teamfight Tactics Gift Card",
      "LibertyX Pins",
      "Lowe's Gift Card",
      "Lululemon Gift Card",
      "Lyft Gift Card",
      "Macy's Gift Card",
      "Marriott Gift Card",
      "Mastercard Gift Card",
      "McDonald's Gift Card",
      "Mediamarkt",
      "Microsoft Gift Card",
      "MolGameCard.com",
      "M&S Gift Card",
      "Myer Gift Card",
      "MyVanilla Prepaid Debit Card",
      "Neiman Marcus Gift Card",
      "Neosurf Gift Card",
      "Netflix Gift Card",
      "Netspend Reload Pack",
      "Newegg Gift Card",
      "Nexon Game Card",
      "Nike Gift Card",
      "Nintendo E-Shop",
      "Nintendo eShop Gift Card",
      "Nordstrom Gift Card",
      "OffGamers Gift Card",
      "Office Depot Gift Card",
      "Old Navy eGift Card",
      "Olive Garden Restaurant Gift Card",
      "One4all Card",
      "OneVanilla Visa/Mastercard Gift Card",
      "Outback Restaurant Gift Card",
      "Ozon Gift Card",
      "Papa Johns Gift Card",
      "Papa Johns GiftCard",
      "PayPal My Cash Gift Card",
      "PC game code - dirt rally",
      "Petco Gift Card",
      "Petsmart Gift Card",
      "Pizza Express Gift Card",
      "Pizza Hut Gift Card",
      "Playstation Network Gift Card",
      "Quiksilver Gift Card",
      "Razer Gold Gift Card",
      "Reebok Gift Card",
      "Reloadable Vanilla Card",
      "Reloadit by Netspend",
      "Restaurant Gift Cards Various Retailers",
      "Restaurants.com Gift Card",
      "Riot Points League of Legends",
      "Roblox Game Card",
      "Safeway Gift Card",
      "Sainsbury",
      "Saks Fifth Avenue Gift Card",
      "Sears Gift Card",
      "Sephora Gift Card",
      "Shoptime Gift Card",
      "Skype Credits",
      "Skype Voucher Code",
      "Southwest Airlines Gift Card",
      "Sport Direct Gift Card",
      "Spotify Gift Card",
      "Staples Gift Card",
      "Starbucks Card",
      "Steam Wallet Gift Card",
      "Stream Gift Card Code",
      "Stubhub Gift Card",
      "Submarino Gift Card",
      "Subway Gift Card",
      "Superdry Gift Card",
      "Target/GameStop/BestBuy Offline",
      "Target Gift Card",
      "Tesco Gift Card",
      "Ticket Premium Gift Card",
      "Ticketmaster Gift Card",
      "Tinder Gift Card",
      "Tmall Gift Card",
      "Transcash Voucher",
      "Twitch Gift Card",
      "Uber Eats Gift Card",
      "Uber Gift Card",
      "Ulta Gift Card",
      "United Airlines Gift Card",
      "UPI Voucher",
      "Valorant Gift Card",
      "Vanilla Reload Card",
      "Vanilla VISA Gift Card",
      "Victoria's Secret Gift Card",
      "Virtual visa mc gift card",
      "Visa Gift Card",
      "Walmart China Card",
      "Walmart E-Gift Code",
      "Walmart Gift Card",
      "Walmart Money Card",
      "Walmart Visa Gift Card",
      "Walmart2Walmart",
      "Whole Foods Market Gift Card",
      "Wildberries Gift Card",
      "Wunschgutschein",
      "Xbox Gift Card",
      "Zappos Gift Card",
      "Zulily E-CODE",
    ],
  },
  {
    key: "mobile_money",
    label: "Mobile money",
    providers: [
      "Airtel Money",
      "AirtelTigo Money",
      "bKash",
      "CBE Birr",
      "CIB Smart Wallet",
      "D17 DigiPost",
      "DaviPlata",
      "Easypaisa",
      "EcoCash",
      "Etisalat Cash",
      "eZ Cash",
      "FNB eWallet",
      "GCash",
      "JazzCash",
      "JoMoPay",
      "M-Pesa",
      "mCash Mobile Payment",
      "Mobile Top-up",
      "MonCash Mobile Wallet",
      "Moov Money (Cote d'Ivoire)",
      "M-Pesa Ethiopia",
      "MTN Mobile Money",
      "Nagad",
      "Natcash",
      "NBE Phone Cash",
      "OPay",
      "Orange Money",
      "PayMaya (Maya) Wallet",
      "Telecel Cash Payment",
      "Tigo Money",
      "Tigo Pesa",
      "UPaisa",
      "Viettel Money",
      "Wave Mobile Wallet",
      "YooMee Mobile Money",
      "Zamtel Kwacha",
    ],
  },
  {
    key: "online_wallet",
    label: "Online wallets",
    providers: [
      "2Checkout",
      "Abra",
      "Afriex",
      "AirPay",
      "AirTM",
      "Alipay",
      "AlipayHK",
      "American Express Bluebird",
      "Apple Pay",
      "Apple Cash",
      "AstroPay Direct",
      "Australia Post Money Transfer",
      "AZA Finance",
      "Bank of America Online Transfer",
      "Bank transfer from ANY Bank",
      "Bank transfer to ANY US bank",
      "Barter by Flutterwave",
      "BBVA Provincial e Banesco",
      "BHIM",
      "BitLipa",
      "Bitsika",
      "bitwallet",
      "Bizum",
      "Bnext",
      "Carbon",
      "Cash App",
      "Cash App Payment",
      "CashU",
      "Cellulant",
      "Chase Quickpay",
      "Checkout",
      "ChimpChange Mobile Banking",
      "Chipper Cash",
      "Current Pay",
      "DANA",
      "Dash App",
      "DotPay Wallet",
      "E-zwich",
      "eCheck",
      "Ecobank Mobile Money",
      "ecoPayz",
      "Electronic Funds Transfer (Bank Deposit)",
      "Email wire transfer",
      "EMQ Send",
      "ePay",
      "Equitel Mobile Money",
      "eSewa",
      "Eversend",
      "Express Union Mobile money",
      "Expresspay",
      "Facebook Messenger Payment",
      "FasaPay Online Payment",
      "Fawry",
      "Fidor same bank transfer",
      "First Bank of Nigeria same bank transfer",
      "Flashpay",
      "Fliqpay",
      "FreeCharge",
      "FriMi",
      "Getcarbon",
      "GLOBAL66",
      "GObank Card Account Transfer",
      "GoFundMe.com",
      "Goods and services",
      "Google Pay",
      "GrabPay",
      "Hello Paisa",
      "Hilton HHonors Points",
      "Hubtel",
      "iCard",
      "ING Direct",
      "ininal",
      "International Remittance",
      "IUDU",
      "Jawwal Pay",
      "JioMoney",
      "Kaiku Card-to-Card Transfer",
      "KaKaoPay",
      "Kash",
      "KoronaPay",
      "Kurepay",
      "Lemon Cash",
      "Lemonade Finance (LemFi)",
      "LeoPay",
      "Line Pay",
      "LiqPay",
      "Lisk LSK",
      "Local Bank Transfer",
      "Lydia",
      "Mercado Pago",
      "MobiKwik Wallet",
      "MobilePay",
      "Mobivi",
      "Moca",
      "MODO",
      "MoMo",
      "Monese Online Transfer",
      "MoneyPolo",
      "MOVii",
      "MovoCash transfer",
      "mPayVN",
      "Mukuru",
      "MyVanilla Card2Card Transfer",
      "Naranja X",
      "Natwest Mobile transfer",
      "NayaPay",
      "Nequi",
      "Neteller",
      "NETTLER",
      "NganLuong",
      "OKPay",
      "Ononpay",
      "Opal Transfer",
      "Other",
      "Other Online Wallets",
      "Other same bank transfers",
      "Oxigen Wallet",
      "Ozow",
      "Paga Wallet",
      "Pagadito",
      "Papara",
      "Paxum",
      "Payee",
      "Payeer",
      "PayM",
      "PayMe",
      "Payoneer",
      "Payoo",
      "PayPal",
      "paysafecard",
      "Payson",
      "Paytm Online Wallet",
      "PayU Wallet",
      "PayZapp",
      "Perfect Money",
      "Personal Pay",
      "PhonePe",
      "Piggyvest",
      "PIM",
      "Pintu",
      "Pockit - Paypoint",
      "Popmoney",
      "Powwi",
      "Pyypl",
      "QIWI",
      "QNB smart wallet",
      "QQ Pay",
      "QRIS (Quick Response Code Indonesian Standard)",
      "Quickteller",
      "Rappi Pay",
      "Regions same bank transfer",
      "Reloadit",
      "Remita",
      "Revolut",
      "Safaricom Bonga Points",
      "Safe.Cash",
      "Same Bank Transfer: CBA, Westpac, INSTANT RELEASE!",
      "Sampath WePay",
      "Sendwave Wallet",
      "Serve",
      "Simbapay",
      "Simple Bank instant transfer",
      "Simple Card peer2peer transfer",
      "Skrill",
      "Slydepay Wallet",
      "SolidTrust Pay",
      "Spektra",
      "spenn",
      "Square up",
      "Straight Talk Reload",
      "Stripe",
      "Swish",
      "T-kash",
      "T-Money Mobile Money",
      "Tap",
      "Tikkie",
      "Toss Wallet",
      "Tpaga",
      "Transfer with specific bank",
      "Transferência Bancos: Intermedium / BB / Santander / Itaú / Bradesco",
      "TrueMoney",
      "Uala",
      "UGO Pay",
      "Uhuru",
      "UnionPay (App)",
      "Uphold",
      "VBank",
      "Veem",
      "Venmo",
      "ViettelPay",
      "Vipps",
      "VoguePay",
      "Volet.com (Formerly Advcash)",
      "Wapipay",
      "WebMoney",
      "WeChat Pay",
      "Wells Fargo SurePay",
      "WorldRemit",
      "Wu-Money.com",
      "Xago",
      "Yandex Money",
      "Yoomoney",
      "Zain Wallet",
      "ZaloPay",
      "Zinli",
    ],
  },
  {
    key: "cash",
    label: "Cash",
    providers: [
      "7 Eleven Store",
      "bank alahli or alinma or alrajhi",
      "Bank deposit electronicTransfer",
      "Bank Transfer from/to any Thai Bank",
      "BB&T Cash Deposit",
      "Bitcoin ATM",
      "BOA❁TD❁WF INSTANT RELEASE!! Cash Deposit",
      "BOA❁TD❁WF❁PNC❁BBT Cash Deposit",
      "BPI Bank Philippines",
      "BPI & Cebuana Lhuiller",
      "Cardless Cash",
      "Cash by Mail",
      "Cash Deposit to Credit Union",
      "Cash Deposit: Financial Institutions",
      "Cash Deposit to Bank",
      "Cash in Person",
      "Eco Cash",
      "Frost Bank Deposit",
      "Hugo Cash",
      "mobile cards topup ,easypaisa,bank transfer",
      "MoneyGram",
      "Nigeria Access Bank",
      "OXXO",
      "Pago Facil",
      "Postal Money Order",
      "Rapipago",
      "Ria Money Transfer",
      "United Bank for Africa (UBA) Cash Desposit",
      "Walmart to walmart",
      "Wari",
      "Western Union",
      "Xpress Money Service",
    ],
  },
  {
    key: "card",
    label: "Debit/Credit cards",
    providers: [
      "AccountNow Prepaid Card",
      "Akimbo",
      "American Express Card",
      "Any Credit/Debit Card",
      "Bluebird by American Express",
      "Card.com Transfer",
      "Credit Card",
      "Debit Card",
      "Discover Credit Card",
      "Entropay Virtual Credit Card",
      "FlashPay (NetSpend)",
      "GoWallet VISA",
      "Green Dot Card",
      "GreenDot Prepaid Debit Card",
      "GreenDot Visa/Mastercard",
      "Kroger Recharge Card",
      "Kroger-to-Kroger Prepaid",
      "Local Card(Green)",
      "Local Card(Red)",
      "Local Card(Yellow)",
      "Mango Card2Card",
      "MIR card",
      "MoneyPak",
      "My Prepaid Center",
      "Netspend Prepaid Debit Card",
      "ONE Debit Card",
      "PayPower",
      "PCS Mastercard",
      "PCS (Prepaid Cash Services)",
      "Postepay",
      "Prepaid credit/ debit cards",
      "Prepaid Debit Card",
      "READYdebit Prepaid Card",
      "RushCard prepaid Visa",
      "Serve Prepaid Debit Cards",
      "Serve-to-Serve (Amex Serve)",
      "Square Cash",
      "Tarjeta Pago24",
      "Tarjeta Prex",
      "Tarjeta Uala",
      "VIABUY Card2Card Transfer",
      "Visa Debit/Credit Card",
    ],
  },
  {
    key: "crypto",
    label: "Crypto",
    providers: [
      "Ardor ARDR",
      "ARK cryptocurrency",
      "Avalanche (AVAX)",
      "Bilira(TRYB)",
      "BiLira (TRYB)",
      "Binance Coin (BNB)",
      "Bitcoin",
      "Bitcoin Cash BCC/BCH",
      "Bitcoin Cash (BCH)",
      "Bitcoin Gold (BTG)",
      "BitShares (BTS)",
      "BNB (Cash App)",
      "BRZ (Brazilian Digital Token)",
      "Bytecoin BCN",
      "Cardano (ADA)",
      "Celestia (TIA)",
      "Celo (CELO)",
      "Chainlink (LINK)",
      "Chiliz",
      "CNHC (CNH Coin)",
      "Credits (CS)",
      "DASH cryptocurrency",
      "DigiByte DGB",
      "Digital e-Rupee",
      "DIM",
      "Dogecoin (DOGE)",
      "eCredits",
      "Electroneum ETN",
      "EOS",
      "Ethereum Classic (ETC)",
      "Ethereum (ETH)",
      "Fantom (FTM)",
      "Fetch.ai (FET)",
      "Hshare HSR",
      "ICON ICX",
      "IDRT",
      "IOTA (MIOTA)",
      "Kin Coin KIN",
      "KuCoin Shares KCS",
      "Litecoin (LTC)",
      "Monero (XMR)",
      "Namecoin NMC",
      "Nano",
      "NEAR Protocol (NEAR)",
      "NEM",
      "NEO",
      "NGNT (Naira Token)",
      "NXT cryptocurrency",
      "OmiseGO OMG",
      "Paxos Gold (PAXG)",
      "Paxos Standard (PAX)",
      "Peercoin (PPC)",
      "Pepe (PEPE)",
      "Polkadot Dot",
      "Populous PPT",
      "Qtum (QTUM)",
      "Reddcoin RDD",
      "Ripple XRP",
      "Ronin : AXS",
      "Ronin : SLP",
      "Sei (SEI)",
      "Shiba Inu (SHIB)",
      "Siacoin (SC)",
      "Solana (SOL)",
      "Status SNT",
      "Steem (STEEM)",
      "Stellar Lumens (XLM)",
      "Stratis (STRAX)",
      "Sui (SUI)",
      "Bittensor (TAO)",
      "Tether USDT",
      "Toncoin",
      "TRON (TRX)",
      "TrueUSD",
      "TrueUSD (TUSD)",
      "USDC",
      "USDT (TRC-20)",
      "VeChain (VET)",
      "Verge XVG",
      "Waves (WAVES)",
      "Zano (Zano)",
      "Zap",
      "Zcash ZEC",
    ],
  },
  {
    key: "goods_services",
    label: "Goods & services",
    providers: [
      "Airline Tickets",
      "Amazon Wishlist",
      "Bill Payment",
      "BitGold",
      "Boost Mobile",
      "Cars",
      "Ding Connect",
      "Domain Name",
      "Game Items",
      "Gold",
      "Google Pay- Gold Locker (MMTC-PAMP)",
      "In-Game Items",
      "Mobile Recharge",
      "NordVPN Subscription",
      "R2 Games Coins",
      "Shop",
      "Special Offer",
      "T-Mobile Refill",
      "Tele2",
      "Vehicles",
    ],
  },
];

export const METHOD_SEPARATOR = " · ";

export function methodString(railLabel: string, provider: string): string {
  return `${railLabel}${METHOD_SEPARATOR}${provider}`;
}

export function railKeyForMethod(method: string): string | null {
  const rail = PAYMENT_RAILS.find((r) => method.startsWith(`${r.label}${METHOD_SEPARATOR}`));
  return rail?.key ?? null;
}

export function railLabelForMethod(method: string): string {
  return method.split(METHOD_SEPARATOR)[0] ?? method;
}

export function providerForMethod(method: string): string {
  return method.split(METHOD_SEPARATOR).slice(1).join(METHOD_SEPARATOR) || method;
}

export const TOTAL_PROVIDER_COUNT = PAYMENT_RAILS.reduce((sum, r) => sum + r.providers.length, 0);

/** Matches a provider anywhere across every rail — used by both the full
 * picker's top-level search and the marketplace's inline quick-search. */
export function searchProviders(query: string): Array<{ rail: PaymentRail; provider: string }> {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const results: Array<{ rail: PaymentRail; provider: string }> = [];
  for (const rail of PAYMENT_RAILS) {
    for (const provider of rail.providers) {
      if (provider.toLowerCase().includes(q) || rail.label.toLowerCase().includes(q)) {
        results.push({ rail, provider });
      }
    }
  }
  return results;
}
