/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedLimitOrdersRouteImport } from './routes/_authenticated/limit-orders'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSwapRouteImport } from './routes/_authenticated/swap'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as TradersUserIdRouteImport } from './routes/traders.$userId'
import { Route as AuthenticatedListingsNewRouteImport } from './routes/_authenticated/listings.new'
import { Route as AuthenticatedTradesIndexRouteImport } from './routes/_authenticated/trades.index'
import { Route as AuthenticatedTradesTradeIdRouteImport } from './routes/_authenticated/trades.$tradeId'
import { Route as ApiPublicCronExecuteLimitOrdersRouteImport } from './routes/api/public/cron/execute-limit-orders'
import { Route as ApiPublicCronExpireTradesRouteImport } from './routes/api/public/cron/expire-trades'
import { Route as ApiPublicWebhooksBtcpayRouteImport } from './routes/api/public/webhooks/btcpay'
import { Route as ApiPublicWebhooksTelegramRouteImport } from './routes/api/public/webhooks/telegram'
import { Route as ApiPublicWebhooksTelegramSetupRouteImport } from './routes/api/public/webhooks/telegram-setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLimitOrdersRoute =
  AuthenticatedLimitOrdersRouteImport.update({
    id: '/limit-orders',
    path: '/limit-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSwapRoute = AuthenticatedSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TradersUserIdRoute = TradersUserIdRouteImport.update({
  id: '/traders/$userId',
  path: '/traders/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedListingsNewRoute =
  AuthenticatedListingsNewRouteImport.update({
    id: '/listings/new',
    path: '/listings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTradesIndexRoute =
  AuthenticatedTradesIndexRouteImport.update({
    id: '/trades/',
    path: '/trades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTradesTradeIdRoute =
  AuthenticatedTradesTradeIdRouteImport.update({
    id: '/trades/$tradeId',
    path: '/trades/$tradeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronExecuteLimitOrdersRoute =
  ApiPublicCronExecuteLimitOrdersRouteImport.update({
    id: '/api/public/cron/execute-limit-orders',
    path: '/api/public/cron/execute-limit-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronExpireTradesRoute =
  ApiPublicCronExpireTradesRouteImport.update({
    id: '/api/public/cron/expire-trades',
    path: '/api/public/cron/expire-trades',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksBtcpayRoute = ApiPublicWebhooksBtcpayRouteImport.update({
  id: '/api/public/webhooks/btcpay',
  path: '/api/public/webhooks/btcpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksTelegramRoute =
  ApiPublicWebhooksTelegramRouteImport.update({
    id: '/api/public/webhooks/telegram',
    path: '/api/public/webhooks/telegram',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksTelegramSetupRoute =
  ApiPublicWebhooksTelegramSetupRouteImport.update({
    id: '/api/public/webhooks/telegram-setup',
    path: '/api/public/webhooks/telegram-setup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fees': typeof FeesRoute
  '/landing': typeof LandingRoute
  '/transparency': typeof TransparencyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/limit-orders': typeof AuthenticatedLimitOrdersRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/swap': typeof AuthenticatedSwapRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/traders/$userId': typeof TradersUserIdRoute
  '/listings/new': typeof AuthenticatedListingsNewRoute
  '/trades/$tradeId': typeof AuthenticatedTradesTradeIdRoute
  '/trades/': typeof AuthenticatedTradesIndexRoute
  '/api/public/cron/execute-limit-orders': typeof ApiPublicCronExecuteLimitOrdersRoute
  '/api/public/cron/expire-trades': typeof ApiPublicCronExpireTradesRoute
  '/api/public/webhooks/btcpay': typeof ApiPublicWebhooksBtcpayRoute
  '/api/public/webhooks/telegram': typeof ApiPublicWebhooksTelegramRoute
  '/api/public/webhooks/telegram-setup': typeof ApiPublicWebhooksTelegramSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fees': typeof FeesRoute
  '/landing': typeof LandingRoute
  '/transparency': typeof TransparencyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/limit-orders': typeof AuthenticatedLimitOrdersRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/swap': typeof AuthenticatedSwapRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/traders/$userId': typeof TradersUserIdRoute
  '/listings/new': typeof AuthenticatedListingsNewRoute
  '/trades/$tradeId': typeof AuthenticatedTradesTradeIdRoute
  '/trades': typeof AuthenticatedTradesIndexRoute
  '/api/public/cron/execute-limit-orders': typeof ApiPublicCronExecuteLimitOrdersRoute
  '/api/public/cron/expire-trades': typeof ApiPublicCronExpireTradesRoute
  '/api/public/webhooks/btcpay': typeof ApiPublicWebhooksBtcpayRoute
  '/api/public/webhooks/telegram': typeof ApiPublicWebhooksTelegramRoute
  '/api/public/webhooks/telegram-setup': typeof ApiPublicWebhooksTelegramSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/fees': typeof FeesRoute
  '/landing': typeof LandingRoute
  '/transparency': typeof TransparencyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/limit-orders': typeof AuthenticatedLimitOrdersRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/swap': typeof AuthenticatedSwapRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/traders/$userId': typeof TradersUserIdRoute
  '/_authenticated/listings/new': typeof AuthenticatedListingsNewRoute
  '/_authenticated/trades/$tradeId': typeof AuthenticatedTradesTradeIdRoute
  '/_authenticated/trades/': typeof AuthenticatedTradesIndexRoute
  '/api/public/cron/execute-limit-orders': typeof ApiPublicCronExecuteLimitOrdersRoute
  '/api/public/cron/expire-trades': typeof ApiPublicCronExpireTradesRoute
  '/api/public/webhooks/btcpay': typeof ApiPublicWebhooksBtcpayRoute
  '/api/public/webhooks/telegram': typeof ApiPublicWebhooksTelegramRoute
  '/api/public/webhooks/telegram-setup': typeof ApiPublicWebhooksTelegramSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fees'
    | '/landing'
    | '/transparency'
    | '/admin'
    | '/limit-orders'
    | '/offers'
    | '/profile'
    | '/settings'
    | '/swap'
    | '/wallet'
    | '/traders/$userId'
    | '/listings/new'
    | '/trades/$tradeId'
    | '/trades/'
    | '/api/public/cron/execute-limit-orders'
    | '/api/public/cron/expire-trades'
    | '/api/public/webhooks/btcpay'
    | '/api/public/webhooks/telegram'
    | '/api/public/webhooks/telegram-setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/fees'
    | '/landing'
    | '/transparency'
    | '/admin'
    | '/limit-orders'
    | '/offers'
    | '/profile'
    | '/settings'
    | '/swap'
    | '/wallet'
    | '/traders/$userId'
    | '/listings/new'
    | '/trades/$tradeId'
    | '/trades'
    | '/api/public/cron/execute-limit-orders'
    | '/api/public/cron/expire-trades'
    | '/api/public/webhooks/btcpay'
    | '/api/public/webhooks/telegram'
    | '/api/public/webhooks/telegram-setup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/fees'
    | '/landing'
    | '/transparency'
    | '/_authenticated/admin'
    | '/_authenticated/limit-orders'
    | '/_authenticated/offers'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/swap'
    | '/_authenticated/wallet'
    | '/traders/$userId'
    | '/_authenticated/listings/new'
    | '/_authenticated/trades/$tradeId'
    | '/_authenticated/trades/'
    | '/api/public/cron/execute-limit-orders'
    | '/api/public/cron/expire-trades'
    | '/api/public/webhooks/btcpay'
    | '/api/public/webhooks/telegram'
    | '/api/public/webhooks/telegram-setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FeesRoute: typeof FeesRoute
  LandingRoute: typeof LandingRoute
  TransparencyRoute: typeof TransparencyRoute
  TradersUserIdRoute: typeof TradersUserIdRoute
  ApiPublicCronExecuteLimitOrdersRoute: typeof ApiPublicCronExecuteLimitOrdersRoute
  ApiPublicCronExpireTradesRoute: typeof ApiPublicCronExpireTradesRoute
  ApiPublicWebhooksBtcpayRoute: typeof ApiPublicWebhooksBtcpayRoute
  ApiPublicWebhooksTelegramRoute: typeof ApiPublicWebhooksTelegramRoute
  ApiPublicWebhooksTelegramSetupRoute: typeof ApiPublicWebhooksTelegramSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/limit-orders': {
      id: '/_authenticated/limit-orders'
      path: '/limit-orders'
      fullPath: '/limit-orders'
      preLoaderRoute: typeof AuthenticatedLimitOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/swap': {
      id: '/_authenticated/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof AuthenticatedSwapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/traders/$userId': {
      id: '/traders/$userId'
      path: '/traders/$userId'
      fullPath: '/traders/$userId'
      preLoaderRoute: typeof TradersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/listings/new': {
      id: '/_authenticated/listings/new'
      path: '/listings/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof AuthenticatedListingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades/': {
      id: '/_authenticated/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof AuthenticatedTradesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades/$tradeId': {
      id: '/_authenticated/trades/$tradeId'
      path: '/trades/$tradeId'
      fullPath: '/trades/$tradeId'
      preLoaderRoute: typeof AuthenticatedTradesTradeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/execute-limit-orders': {
      id: '/api/public/cron/execute-limit-orders'
      path: '/api/public/cron/execute-limit-orders'
      fullPath: '/api/public/cron/execute-limit-orders'
      preLoaderRoute: typeof ApiPublicCronExecuteLimitOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/expire-trades': {
      id: '/api/public/cron/expire-trades'
      path: '/api/public/cron/expire-trades'
      fullPath: '/api/public/cron/expire-trades'
      preLoaderRoute: typeof ApiPublicCronExpireTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/btcpay': {
      id: '/api/public/webhooks/btcpay'
      path: '/api/public/webhooks/btcpay'
      fullPath: '/api/public/webhooks/btcpay'
      preLoaderRoute: typeof ApiPublicWebhooksBtcpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/telegram': {
      id: '/api/public/webhooks/telegram'
      path: '/api/public/webhooks/telegram'
      fullPath: '/api/public/webhooks/telegram'
      preLoaderRoute: typeof ApiPublicWebhooksTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/telegram-setup': {
      id: '/api/public/webhooks/telegram-setup'
      path: '/api/public/webhooks/telegram-setup'
      fullPath: '/api/public/webhooks/telegram-setup'
      preLoaderRoute: typeof ApiPublicWebhooksTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedLimitOrdersRoute: typeof AuthenticatedLimitOrdersRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSwapRoute: typeof AuthenticatedSwapRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedListingsNewRoute: typeof AuthenticatedListingsNewRoute
  AuthenticatedTradesTradeIdRoute: typeof AuthenticatedTradesTradeIdRoute
  AuthenticatedTradesIndexRoute: typeof AuthenticatedTradesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedLimitOrdersRoute: AuthenticatedLimitOrdersRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSwapRoute: AuthenticatedSwapRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedListingsNewRoute: AuthenticatedListingsNewRoute,
  AuthenticatedTradesTradeIdRoute: AuthenticatedTradesTradeIdRoute,
  AuthenticatedTradesIndexRoute: AuthenticatedTradesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FeesRoute: FeesRoute,
  LandingRoute: LandingRoute,
  TransparencyRoute: TransparencyRoute,
  TradersUserIdRoute: TradersUserIdRoute,
  ApiPublicCronExecuteLimitOrdersRoute: ApiPublicCronExecuteLimitOrdersRoute,
  ApiPublicCronExpireTradesRoute: ApiPublicCronExpireTradesRoute,
  ApiPublicWebhooksBtcpayRoute: ApiPublicWebhooksBtcpayRoute,
  ApiPublicWebhooksTelegramRoute: ApiPublicWebhooksTelegramRoute,
  ApiPublicWebhooksTelegramSetupRoute: ApiPublicWebhooksTelegramSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
