/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedListingsNewRouteImport } from './routes/_authenticated/listings.new'
import { Route as AuthenticatedTradesIndexRouteImport } from './routes/_authenticated/trades.index'
import { Route as AuthenticatedTradesTradeIdRouteImport } from './routes/_authenticated/trades.$tradeId'
import { Route as ApiPublicWebhooksNowpaymentsDepositRouteImport } from './routes/api/public/webhooks/nowpayments/deposit'
import { Route as ApiPublicWebhooksNowpaymentsPayoutRouteImport } from './routes/api/public/webhooks/nowpayments/payout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListingsNewRoute =
  AuthenticatedListingsNewRouteImport.update({
    id: '/listings/new',
    path: '/listings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTradesIndexRoute =
  AuthenticatedTradesIndexRouteImport.update({
    id: '/trades/',
    path: '/trades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTradesTradeIdRoute =
  AuthenticatedTradesTradeIdRouteImport.update({
    id: '/trades/$tradeId',
    path: '/trades/$tradeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksNowpaymentsDepositRoute =
  ApiPublicWebhooksNowpaymentsDepositRouteImport.update({
    id: '/api/public/webhooks/nowpayments/deposit',
    path: '/api/public/webhooks/nowpayments/deposit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksNowpaymentsPayoutRoute =
  ApiPublicWebhooksNowpaymentsPayoutRouteImport.update({
    id: '/api/public/webhooks/nowpayments/payout',
    path: '/api/public/webhooks/nowpayments/payout',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/listings/new': typeof AuthenticatedListingsNewRoute
  '/trades/$tradeId': typeof AuthenticatedTradesTradeIdRoute
  '/trades/': typeof AuthenticatedTradesIndexRoute
  '/api/public/webhooks/nowpayments/deposit': typeof ApiPublicWebhooksNowpaymentsDepositRoute
  '/api/public/webhooks/nowpayments/payout': typeof ApiPublicWebhooksNowpaymentsPayoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/listings/new': typeof AuthenticatedListingsNewRoute
  '/trades/$tradeId': typeof AuthenticatedTradesTradeIdRoute
  '/trades': typeof AuthenticatedTradesIndexRoute
  '/api/public/webhooks/nowpayments/deposit': typeof ApiPublicWebhooksNowpaymentsDepositRoute
  '/api/public/webhooks/nowpayments/payout': typeof ApiPublicWebhooksNowpaymentsPayoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/listings/new': typeof AuthenticatedListingsNewRoute
  '/_authenticated/trades/$tradeId': typeof AuthenticatedTradesTradeIdRoute
  '/_authenticated/trades/': typeof AuthenticatedTradesIndexRoute
  '/api/public/webhooks/nowpayments/deposit': typeof ApiPublicWebhooksNowpaymentsDepositRoute
  '/api/public/webhooks/nowpayments/payout': typeof ApiPublicWebhooksNowpaymentsPayoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/profile'
    | '/settings'
    | '/wallet'
    | '/listings/new'
    | '/trades/$tradeId'
    | '/trades/'
    | '/api/public/webhooks/nowpayments/deposit'
    | '/api/public/webhooks/nowpayments/payout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/profile'
    | '/settings'
    | '/wallet'
    | '/listings/new'
    | '/trades/$tradeId'
    | '/trades'
    | '/api/public/webhooks/nowpayments/deposit'
    | '/api/public/webhooks/nowpayments/payout'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/wallet'
    | '/_authenticated/listings/new'
    | '/_authenticated/trades/$tradeId'
    | '/_authenticated/trades/'
    | '/api/public/webhooks/nowpayments/deposit'
    | '/api/public/webhooks/nowpayments/payout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWebhooksNowpaymentsDepositRoute: typeof ApiPublicWebhooksNowpaymentsDepositRoute
  ApiPublicWebhooksNowpaymentsPayoutRoute: typeof ApiPublicWebhooksNowpaymentsPayoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings/new': {
      id: '/_authenticated/listings/new'
      path: '/listings/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof AuthenticatedListingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades/': {
      id: '/_authenticated/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof AuthenticatedTradesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades/$tradeId': {
      id: '/_authenticated/trades/$tradeId'
      path: '/trades/$tradeId'
      fullPath: '/trades/$tradeId'
      preLoaderRoute: typeof AuthenticatedTradesTradeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/nowpayments/deposit': {
      id: '/api/public/webhooks/nowpayments/deposit'
      path: '/api/public/webhooks/nowpayments/deposit'
      fullPath: '/api/public/webhooks/nowpayments/deposit'
      preLoaderRoute: typeof ApiPublicWebhooksNowpaymentsDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/nowpayments/payout': {
      id: '/api/public/webhooks/nowpayments/payout'
      path: '/api/public/webhooks/nowpayments/payout'
      fullPath: '/api/public/webhooks/nowpayments/payout'
      preLoaderRoute: typeof ApiPublicWebhooksNowpaymentsPayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedListingsNewRoute: typeof AuthenticatedListingsNewRoute
  AuthenticatedTradesTradeIdRoute: typeof AuthenticatedTradesTradeIdRoute
  AuthenticatedTradesIndexRoute: typeof AuthenticatedTradesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedListingsNewRoute: AuthenticatedListingsNewRoute,
  AuthenticatedTradesTradeIdRoute: AuthenticatedTradesTradeIdRoute,
  AuthenticatedTradesIndexRoute: AuthenticatedTradesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWebhooksNowpaymentsDepositRoute:
    ApiPublicWebhooksNowpaymentsDepositRoute,
  ApiPublicWebhooksNowpaymentsPayoutRoute:
    ApiPublicWebhooksNowpaymentsPayoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
